# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180101_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cpation',
            new_name='caption',
        ),
    ]
